name: input_mask
description: A Dart interface for RobinHerbotss InputMask
version: 0.0.2
homepage: https://github.com/jodinathan/input_mask

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  pedantic: any
