name: input_mask
description: A Dart interface for RobinHerbots InputMask
version: 0.0.2
homepage: https://github.com/jodinathan/input_mask

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  lints: ^1.0.1
